version: '3'
services:
  db:
    image: postgres
    container_name: blogy-db
    environment:
      - POSTGRES_USER=blogy
      - POSTGRES_PASSWORD=password
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  api:
    build: .
    container_name: blogy-api
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db